# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-IE-PermanentTSB
version:      0.02
version_from: lib/Finance/Bank/IE/PermanentTSB.pm
installdirs:  site
requires:
    Date::Calc:                    0
    HTML::TokeParser::Simple:      0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
